---
- name: restart qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: yes
    state: restarted
  become: true
  become_user: root

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: restarted
  become: true
  become_user: root
