---
- name: Install Desktop Environment
  community.general.pacman:
    name: '{{ item }}'
    state: present
  loop: '{{ desktop_packages }}'
  become: true
  become_user: root

# workaround since the module cant find ulauncher 
- name: Install ulauncher using yay
  command: yay -S --noconfirm ulauncher
  register: install_result
  failed_when: install_result.rc != 0
  changed_when: "'installed' in install_result.stdout or 'upgraded' in install_result.stdout"
  ignore_errors: no

- name: Enable and start GDM service
  ansible.builtin.systemd:
    name: gdm
    enabled: yes
    state: started
  become: true
  become_user: root

- name: Enable and start Bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: yes
    state: started
  become: true
  become_user: root
