---
- name: sync dotfiles
  ansible.builtin.git:
    # repo: git@github.com:caiodelgadonew/dotfiles.git
    repo: https://github.com/caiodelgadonew/dotfiles.git
    dest: '/home/{{ ansible_user_id}}/dotfiles'
    update: true
    force: true
    depth: 1

- name: Stow tmux
  ansible.builtin.command:
    chdir: '/home/{{ ansible_user_id}}/dotfiles'
    cmd: stow tmux
    creates: '/home/{{ ansible_user_id }}/.tmux.conf'

- name: stow alacritty
  ansible.builtin.command:
    chdir: '/home/{{ ansible_user_id}}/dotfiles'
    cmd: stow alacritty
    creates: '/home/{{ ansible_user_id }}/.config/alacritty.toml'

- name: stow kitty
  ansible.builtin.command:
    chdir: '/home/{{ ansible_user_id}}/dotfiles'
    cmd: stow kitty
    creates: '/home/{{ ansible_user_id }}/.config/kitty/kitty.conf'

- name: Stow neovim
  ansible.builtin.command:
    chdir: '/home/{{ ansible_user_id}}/dotfiles'
    cmd: stow nvim
    creates: '/home/{{ ansible_user_id }}/.config/nvim/'

- name: Stow i3
  ansible.builtin.command:
    chdir: '/home/{{ ansible_user_id}}/dotfiles'
    cmd: stow i3
    creates: '/home/{{ ansible_user_id }}/.config/i3/'
  when: desktop_environment | default(false) | bool

- name: Stow picom
  ansible.builtin.command:
    chdir: '/home/{{ ansible_user_id}}/dotfiles'
    cmd: stow picom
    creates: '/home/{{ ansible_user_id }}/.config/picom/'
  when: desktop_environment | default(false) | bool

- name: Stow polybar
  ansible.builtin.command:
    chdir: '/home/{{ ansible_user_id}}/dotfiles'
    cmd: stow polybar
    creates: '/home/{{ ansible_user_id }}/.config/polybar/'
  when: desktop_environment | default(false) | bool

- name: Stow ulauncher
  ansible.builtin.command:
    chdir: '/home/{{ ansible_user_id}}/dotfiles'
    cmd: stow ulauncher
    creates: '/home/{{ ansible_user_id }}/.config/ulauncher/'
  when: desktop_environment | default(false) | bool
