---
- name: Install Software with YAY
  yay:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ yay_packages }}"
  become: true

# Separate step since its in beta and you need to have access to it
- name: Install Ghostty
  yay:
    name: ghostty-git
    state: present
    update_cache: yes
  when: ghostty_install | default (false) | bool

- name: Create symlink from nvim to vim
  ansible.builtin.file:
    src: /usr/bin/nvim
    dest: /usr/bin/vim
    state: link
  become_user: root
